package Objects;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * <ul>
 * <li>The DatesReserv class represents a reservation of a book in a library
 * system. It includes information about the start and end dates of the
 * reservation, as well as a unique identifier.</li>
 * <li>The DatesReserv class is annotated with the @Entity annotation,
 * indicating that it is a JPA entity. It is also annotated with the @Table
 * annotation, which specifies the name of the database table that will be used
 * to store DatesReserv objects. The class has several fields, each of which is
 * annotated with the @Column annotation to specify the corresponding column in
 * the database table.</li>
 * <li>The idres field is annotated with the @Id and @GeneratedValue annotations
 * to indicate that it is the primary key and its value will be generated by the
 * database. The debut and fin fields represent the start and end dates of the
 * reservation, respectively.</li>
 * <li>The livre field is annotated with the @OneToOne and @JoinTable
 * annotations to indicate that it is a one-to-one relationship between the
 * DatesReserv and Livre entities.</li>
 * <li>The @JoinTable annotation specifies the join table and join columns for
 * the relationship.</li>
 * </ul>
 * 
 * @author Sarah Katz
 *
 */
@Entity
@Table(name = "reserv")
public class DatesReserv {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idres")
	private int idres;
	@Column(name = "debut")
	private Date debut;
	@Column(name = "fin")
	private Date fin;
	@OneToOne(cascade = CascadeType.ALL)
	@JoinTable(name = "reserver", joinColumns = @JoinColumn(name = "idres"), inverseJoinColumns = @JoinColumn(name = "idlivre"))
	private Livre livre;

	public DatesReserv() {
	}

	/**
	 * @param debut
	 * @param fin
	 * @param livre
	 */
	public DatesReserv(final Date debut, final Date fin, final Livre livre) {
		this.debut = debut;
		this.fin = fin;
		this.livre = livre;
	}

	/**
	 * @return the idres
	 */
	public int getIdres() {
		return idres;
	}

	/**
	 * @param idres the idres to set
	 */
	public void setIdres(int idres) {
		this.idres = idres;
	}

	/**
	 * @return the debut
	 */
	public Date getDebut() {
		return debut;
	}

	/**
	 * @param debut the debut to set
	 */
	public void setDebut(Date debut) {
		this.debut = debut;
	}

	/**
	 * @return the fin
	 */
	public Date getFin() {
		return fin;
	}

	/**
	 * @param fin the fin to set
	 */
	public void setFin(Date fin) {
		this.fin = fin;
	}

}
