package Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * <ul>
 * <li>The Livre class represents a book in a library system. It includes
 * information about the title, author, genre, number of pages, and availability
 * of the book. It also includes a unique identifier and a reference number for
 * the book.</li>
 * <li>The Livre class is annotated with the @Entity annotation, indicating that
 * it is a JPA entity. It is also annotated with three @NamedQuery annotations,
 * which define named queries that can be used to retrieve or update Livre
 * objects from the database.</li>
 * <li>The @Table annotation specifies the name of the database table that will
 * be used to store Livre objects. The class has several fields, each of which
 * is annotated with the @Column annotation to specify the corresponding column
 * in the database table. The idlivre field is annotated with the @Id
 * and @GeneratedValue annotations to indicate that it is the primary key and
 * its value will be generated by the database.</li>
 * <li>The disponible field is a boolean that indicates whether the book is
 * currently available for loan.</li>
 * </ul>
 * 
 * @author Sarah Katz
 *
 */
@Entity
@NamedQuery(name = "Livre.showAll", query = "SELECT l FROM Livre l ORDER BY l.ref")
@NamedQuery(name = "Livre.searchAuthor", query = "SELECT l FROM Livre l WHERE l.auteur LIKE :inputTitle")
@NamedQuery(name = "Livre.setChanges", query = "UPDATE Livre l SET titre = :titre, auteur = :auteur, genre = :genre, pages = :pages, ref = :ref WHERE titre = :oldTitle")
@Table(name = "livre")
public class Livre {
	@Column(name = "titre")
	private String titre;
	@Column(name = "auteur")
	private String auteur;
	@Column(name = "genre")
	private String genre;
	@Column(name = "pages")
	private int pages;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idlivre")
	private int idlivre;
	@Column(name = "disponible")
	private boolean disponible;
	@Column(name = "ref")
	private String ref;

	public Livre() {
	}

	/**
	 * 
	 * Constructs a new Livre object with the given title, author, genre, number of
	 * pages, and reference. The new Livre object is initialized with a default
	 * value of true for the disponible field, indicating that it is available for
	 * borrowing.
	 * 
	 * @param titre  the title of the book
	 * @param auteur the author of the book
	 * @param genre  the genre of the book
	 * @param pages  the number of pages in the book
	 * @param ref    the reference number of the book
	 */
	public Livre(String titre, String auteur, String genre, int pages, String ref) {
		this.titre = titre;
		this.auteur = auteur;
		this.genre = genre;
		this.pages = pages;
		this.disponible = true;
		this.ref = ref;
	}

	/**
	 * Gets and returns all infos about a book
	 * 
	 * @return the book's title, author, genre, page number and reference number
	 */
	public StringBuilder showBookInfos() {
		StringBuilder result = new StringBuilder();
		result.append("Titre : ").append(this.getTitre()).append("\n");
		result.append("Auteur.ice : ").append(this.getAuteur()).append("\n");
		result.append("Genre : ").append(this.getGenre()).append("\n");
		result.append("Nombre de pages : ").append(this.getPages()).append("\n");
		result.append("Référence : ").append(this.getRef()).append("\n");
		return result;
	}

	/**
	 * @return the titre
	 */
	public String getTitre() {
		return titre;
	}

	/**
	 * @param titre the title to set
	 */
	public void setTitre(String titre) {
		this.titre = titre;
	}

	/**
	 * @return the auteur
	 */
	public String getAuteur() {
		return auteur;
	}

	/**
	 * @param auteur the author to set
	 */
	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

	/**
	 * @return the genre
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * @param genre the genre to set
	 */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/**
	 * @return the number of  pages
	 */
	public int getPages() {
		return pages;
	}

	/**
	 * @param pages the number of pages to set
	 */
	public void setPages(int pages) {
		this.pages = pages;
	}

	/**
	 * @return the idlivre
	 */
	public int getIdlivre() {
		return idlivre;
	}

	/**
	 * @param idlivre the id to set
	 */
	public void setIdlivre(int idlivre) {
		this.idlivre = idlivre;
	}

	/**
	 * @return the availability
	 */
	public boolean isDisponible() {
		return disponible;
	}

	/**
	 * @param disponible the availability of the book
	 */
	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

	/**
	 * @return the book reference
	 */
	public String getRef() {
		return ref;
	}

	/**
	 * @param ref the book reference to set
	 */
	public void setRef(String ref) {
		this.ref = ref;
	}

}
